### ISSUE TITLE
STDOUT/STDERR pass-through for wrapped command

### ISSUE THREAD

**Issue by sokratisg** [sampointer/kapo#9]
First of all, thank you for releasing kapo. It matches perfectly the use case of remotely health checking applications/containers of non-network based apps.

We intent to use it for some [Sidekiq ](http://sidekiq.org/) dedicated containers but we couldn't find a way to keep sidekiq's original stdout/stderr logging. The moment container starts, its logging is suppressed by kapo. Just an excerpt from ```docker-compose logs sidekiq```:
```
...
sidekiq_1        | Bundled gems are installed into /usr/local/bundle.
sidekiq_1        | INFO[0000] binding to 0.0.0.0:6666                      
sidekiq_1        | INFO[0000] running /usr/local/bin/bundle exec sidekiq   
```

When we run sidekiq without kapo, we have all stdout/stderr passed to docker logs successfully:
```
...
sidekiq_1        | Bundled gems are installed into /usr/local/bundle.
sidekiq_1        | 2017-06-28T12:13:39.102Z 51 TID-7bn68 INFO: Booting Sidekiq 5.0.0 with redis options {:url=>"redis://redis:6379/2"}
sidekiq_1        | 
sidekiq_1        | 
sidekiq_1        |          m,
sidekiq_1        |          `$b
sidekiq_1        |     .ss,  $$:         .,d$
sidekiq_1        |     `$$P,d$P'    .,md$P"'
sidekiq_1        |      ,$$$$$bmmd$$$P^'
sidekiq_1        |    .d$$$$$$$$$$P'
sidekiq_1        |    $$^' `"^$$$'       ____  _     _      _    _
sidekiq_1        |    $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
sidekiq_1        |    `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
sidekiq_1        |           $$:         ___) | | (_| |  __/   <| | (_| |
sidekiq_1        |           $$         |____/|_|\__,_|\___|_|\_\_|\__, |
sidekiq_1        |         .d$$                                       |_|
sidekiq_1        | 
sidekiq_1        | 2017-06-28T12:13:39.291Z 51 TID-7bn68 INFO: Running in ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
sidekiq_1        | 2017-06-28T12:13:39.291Z 51 TID-7bn68 INFO: See LICENSE and the LGPL-3.0 for licensing details.
sidekiq_1        | 2017-06-28T12:13:39.291Z 51 TID-7bn68 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
...
```

Does kapo have any runtime option enabling stdout/stderr passthrough or is this something out of scope?

**Comment by sampointer** [comment]
Thanks for logging an issue, and I'm glad you're finding it useful so-far.

I'll do some digging and thinking and see what makes the most sense when Kapo is used in situations whereby logging is essentially the capture of STDOUT and STDERR.

The original conception is that supervised processes would either redirect their own STDOUT or would be writing directly to a logging daemon of some kind. However, it does seem like a common pattern in the Docker (and systemd, for that matter) world is to passively slurp fds 1 and 2.

**Comment by sokratisg** [comment]
That's exactly my point! :)
Almost, if not all Docker related logging solutions rely of docker's logging drivers which in their turn rely on STDOUT and STDERR for each container's logging.

Let me know how the thinking goes, meanwhile I find it a more than proper opportunity to start learning Golang. I'll submit a PR if I manage to do that on my own spare time.

**Comment by sampointer** [comment]
Great! I've started a gitter room for this project (there's a badge in the README) if you'd like to talk through any PR (or indeed anything) outside of the github issues.

**Comment by sampointer** [comment]
Branch `pass-thru_stdout_stderr` contains a first-punt implementation of stdout and stderr capturing. It headadds the global options `--stdout`, `--stderr` and `--stdlog` - the latter causes Kapo to emit each line of stdout/stderr read as a log from Kapo. This is to allow timstamp information to be captured when the supervised program is just printing strings.

I ran a `while do; true; echo blah; done` bash script under the `run` subcommand with all 3 options turned on for ~45 minutes, producing 232017270 lines of logging. Under Expvarmon looked to have a fairly decently saw-tooth memory profile, so I don't think I've done anything terribly daft.

Please give a build from that branch a go (the artifacts from the build are here: https://circleci.com/gh/sampointer/kapo/96#artifacts/containers/0) and let me know how you get on.

**Comment by sokratisg** [comment]
As one famous CEO would say: "It just works!" :+1: 

Used all three new options and output was properly handled. Didn't do any extensive testing but the first taste is you nailed this one. When do you plan to create new artifacts here in GH? Asking because this is the source I'm using in the respective Dockerfile.

**Comment by sampointer** [comment]
0.6.0 has been tagged, built and linked to from the README (and of course, gh has the release tarball).
